### ISSUE TITLE
Upgrade analytics

### ISSUE THREAD

**Issue by thomasmarshall** [withassociates/slices#100] opened 2015-08-04 13:24 UTC
Should we update the `google_analytics_tracking_code` method to use the new style tracking code?

https://github.com/withassociates/slices/blob/bd20969ffcf2edd3bf6ef220906d974453aadec0/app/helpers/pages_helper.rb#L90-L108

**Comment by erino** [comment] 2015-08-04 13:32
I was thinking that we should remove the `google_analytics_tracking_code` method, it's not that hard to copy the code from Google. The `add_tracking_code` method is the timesaving part.

**Comment by thomasmarshall** [comment] 2015-08-04 13:36
Yep, I agree with that.

**Comment by bensymonds** [comment] 2015-09-02 15:33
Can we just close this issue, given we have https://github.com/withassociates/slices/pull/101? I never really know what the best thing to do is when there's a PR covering an issue. It seems like the issue is now tracked by the PR, so we don't need the issue any more.

**Comment by erino** [comment] 2015-09-02 15:36
This is now covered in #101

**Closed by erino** 2015-09-02 15:36 UTC
